#!/usr/bin/env bash
# Function to display subdomain information
display_info() {
    local domain=$1
    local subdomain=$2

    if [ -n "$subdomain" ]; then
	record_type="$(dig $subdomain."$1" | grep -A1 'ANSWER SECTION:'| tail -1 | awk '{print $4}')"
        destination=$(dig +short "$subdomain.$domain" | awk 'NR==1{print}')
        echo "The subdomain $subdomain is a $record_type record and points to $destination"
    else
        subdomains=("www" "lb-01" "web-01" "web-02")
        for sub in "${subdomains[@]}"; do
	    record_type="$(dig $sub."$1" | grep -A1 'ANSWER SECTION:'| tail -1 | awk '{print $4}')"
            destination=$(dig +short "$sub.$domain" | awk 'NR==1{print}')
            echo "The subdomain $sub is a $record_type record and points to $destination"
        done
    fi
}

# Check for correct number of arguments
if [ "$#" -ne 1 ] && [ "$#" -ne 2 ]; then
    echo "Usage: $0 domain [subdomain]"
    exit 1
fi

# Call the function
display_info "$1" "$2"
