#!/usr/bin/env bash

# Update package list and install nginx
sudo apt-get update -y
sudo apt-get install -y nginx

# Create a default HTML file with "Hello World!"
echo "Hello World!" > /usr/share/nginx/html/index.html

service nginx restart
