#!/usr/bin/env bash
# Update package list and install nginx
sudo apt-get update -y
sudo apt-get install -y nginx
file1=/var/www/html/index.html
file=/etc/nginx/sites-available/default
sudo bash -c "echo 'Hello World!' > $file1"
phrase="location /redirect_me {\nreturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}\n"
sudo sed -i "30i $phrase" $file
sudo service nginx restart
