#!/usr/bin/env bash
# Update package list and install nginx
sudo apt-get update -y
sudo apt-get install -y nginx
file1=/var/www/html/index.html
file=/etc/nginx/sites-available/default
sudo bash -c "echo 'Hello World!' > $file1"
phrase="location /redirect_me {\nreturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}\n"
sudo sed -i "30i $phrase" $file
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null
NEW_RULE="\\\n\terror_page 404 /404.html;\n\n\tlocation = /404.html {\n\t\tinternal;\n\t}\n"
sudo sed -i "53i $NEW_RULE" /etc/nginx/sites-available/default
sudo service nginx restart
