#!/usr/bin/env bash
# Update package list and install nginx
sudo apt-get update -y
sudo apt-get install -y nginx
file1=/var/www/html/index.html
file=/etc/nginx/sites-available/default
sudo bash -c "echo 'Hello World!' > $file1"
phrase="location /redirect_me {\nreturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}\n"
sudo sed -i "30i $phrase" $file
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
phrase2="error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /usr/share/nginx/html;\ninternal;\n}\n"
sudo sed -i "30i $phrase2" $file
sudo service nginx restart
