#!/usr/bin/env bash

# Check if the school key pair files already exist
if [[ -f "school" || -f "school.pub" ]]; then
  echo "The 'school' key pair already exists."
  exit 1
fi

# Create an RSA key pair with 4096 bits and a passphrase 'betty'
ssh-keygen -t rsa -b 4096 -f school -N 'betty'
